from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from datetime import datetime


# ===== Page Number Footer =====
def add_page_number(canvas, doc):
    page_num = canvas.getPageNumber()
    text = f"Page {page_num}"
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(580, 20, text)


def generate_pdf(df, insights, narrative):

    filename = f"AI_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"

    doc = SimpleDocTemplate(
        filename,
        pagesize=letter,
        leftMargin=50,
        rightMargin=50,
        topMargin=60,
        bottomMargin=50,
    )

    styles = getSampleStyleSheet()

    # ===== Styles =====
    title = ParagraphStyle("title", parent=styles["Title"], alignment=1)
    subtitle = ParagraphStyle("subtitle", parent=styles["Heading2"], alignment=1, textColor=colors.grey)
    section = ParagraphStyle("section", parent=styles["Heading2"], spaceBefore=18, spaceAfter=10)
    body = ParagraphStyle("body", parent=styles["Normal"], leading=14)

    elements = []

    # ================= COVER =================
    elements.append(Spacer(1, 120))
    elements.append(Paragraph("AI Data Analyst", title))
    elements.append(Paragraph("Executive Intelligence Report", subtitle))
    elements.append(Spacer(1, 30))
    elements.append(Paragraph(datetime.now().strftime("%d %B %Y"), subtitle))
    elements.append(PageBreak())

    # ================= SUMMARY =================
    elements.append(Paragraph("Executive Summary", section))
    elements.append(Paragraph(narrative, body))

    # ================= DATASET OVERVIEW =================
    rows, cols = df.shape
    missing = int(df.isnull().sum().sum())

    elements.append(Paragraph("Dataset Overview", section))

    overview_data = [
        ["Metric", "Value"],
        ["Rows", f"{rows:,}"],
        ["Columns", cols],
        ["Missing Values", missing],
    ]

    overview_table = Table(overview_data, colWidths=[2.5 * inch, 2.5 * inch])
    overview_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ALIGN", (1, 1), (-1, -1), "CENTER"),
    ]))
    elements.append(overview_table)

    # ================= DATA STORY =================
    elements.append(Paragraph("Data Story", section))

    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    id_cols = [c for c in df.columns if df[c].nunique() == len(df)]
    useful_numeric = [c for c in numeric_cols if c not in id_cols]

    corr_text = "Not enough numeric data"
    if len(useful_numeric) > 1:
        corr = df[useful_numeric].corr().abs()
        for i in corr.index:
            corr.loc[i, i] = 0
        pair = corr.unstack().sort_values(ascending=False).idxmax()
        corr_text = f"{pair[0]} ↔ {pair[1]}"

    story = (
        f"This dataset contains {rows:,} records across {cols} features. "
        f"The strongest relationship is between {corr_text}. "
        f"The structure suggests suitability for analytics and modeling."
    )
    elements.append(Paragraph(story, body))

    # ================= INSIGHTS =================
    elements.append(Paragraph("Key Insights", section))
    for ins in insights:
        elements.append(Paragraph(f"• {ins}", body))

    # ================= SMART STAT TABLE =================
    elements.append(Paragraph("Statistical Snapshot", section))

    desc = df.describe().round(2)

    # Limit columns to avoid overflow
    max_cols = 6
    selected_cols = desc.columns[:max_cols]

    stat_data = [["Metric"] + list(selected_cols)]

    for idx, row in desc.iterrows():
        stat_data.append([idx] + [row[col] for col in selected_cols])

    # Auto-fit width
    col_width = 450 / (len(selected_cols) + 1)
    col_widths = [col_width] * (len(selected_cols) + 1)

    stat_table = Table(stat_data, colWidths=col_widths)
    stat_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
    ]))
    elements.append(stat_table)

    # ================= FOOTER =================
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by AI Data Analyst • Meghana Ullas", styles["Italic"]))

    doc.build(elements, onLaterPages=add_page_number, onFirstPage=add_page_number)
    return filename